#!/usr/bin/env bash
# Create (or reuse) a Neon project for Slip and print DATABASE_URL for OCI.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${ROOT}/deploy/oci/.env.neon"
mkdir -p "$(dirname "$ENV_FILE")"

if ! command -v neonctl >/dev/null 2>&1; then
  echo "Install neonctl: brew install neonctl" >&2
  exit 1
fi

echo "==> Neon auth (browser). Re-run if session expired."
neonctl auth || neon auth || true

PROJECT_NAME="${NEON_PROJECT_NAME:-slip-pass-engine}"
ORG_FLAG=()
if [[ -n "${NEON_ORG_ID:-}" ]]; then
  ORG_FLAG=(--org-id "$NEON_ORG_ID")
fi

echo "==> Ensuring Neon project: $PROJECT_NAME"
# List projects; create if missing
if neonctl projects list --output json 2>/dev/null | python3 -c "import sys,json; d=json.load(sys.stdin); ids=[p.get('id') for p in (d if isinstance(d,list) else d.get('projects',d.get('items',[]))) if p.get('name')==sys.argv[1]]; print(ids[0] if ids else '')" "$PROJECT_NAME" | grep -q .; then
  PROJECT_ID=$(neonctl projects list --output json | python3 -c "import sys,json; d=json.load(sys.stdin); items=d if isinstance(d,list) else d.get('projects',d.get('items',[]));
print(next(p['id'] for p in items if p.get('name')==sys.argv[1]))" "$PROJECT_NAME")
  echo "Using existing project $PROJECT_ID"
else
  PROJECT_ID=$(neonctl projects create --name "$PROJECT_NAME" "${ORG_FLAG[@]}" --output json | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('project',d).get('id'))")
  echo "Created project $PROJECT_ID"
fi

echo "==> Fetching connection URI"
CONN=$(neonctl connection-string --project-id "$PROJECT_ID" --role-name neondb_owner --database-name neondb --pooled --output json 2>/dev/null \
  | python3 -c "import sys,json; d=json.load(sys.stdin); print(d if isinstance(d,str) else d.get('uri') or d.get('connection_uri') or d.get('connectionString') or '')" \
  || neonctl connection-string --project-id "$PROJECT_ID" --pooled)

if [[ -z "$CONN" ]]; then
  echo "Failed to get connection string" >&2
  exit 1
fi

# Never echo password to stdout permanently — write env file (gitignored)
umask 077
cat > "$ENV_FILE" <<ENV
# Generated by scripts/setup-neon.sh — do not commit
NEON_PROJECT_ID=$PROJECT_ID
DATABASE_URL=$CONN
SPRING_PROFILES_ACTIVE=neon
FLYWAY_ENABLED=true
JPA_DDL_AUTO=validate
DATABASE_DRIVER=org.postgresql.Driver
ENV

echo "Wrote $ENV_FILE"
echo "Project: $PROJECT_ID"
echo "Next: source deploy/oci/.env.neon and run scripts/setup-oci.sh / deploy/oci/provision.sh"
