-- Stitch HTML: full face-field schemas for every apple_wallet_template_*.
UPDATE brands SET required_fields = '["event", "seat", "qr_data"]'::jsonb, optional_fields = '["venue", "screen", "booking_id", "time", "date", "format", "certification", "language", "fnb", "pickup_counter"]'::jsonb, updated_at = NOW() WHERE id = 'bookmyshow';
UPDATE brands SET required_fields = '["event", "qr_data"]'::jsonb, optional_fields = '["venue", "seat", "screen", "tier", "gate", "zone", "passholder", "booking_id", "time", "date", "format", "age_gate", "cashless_balance", "venue_detail", "access"]'::jsonb, updated_at = NOW() WHERE id = 'district';
UPDATE brands SET required_fields = '["origin", "destination", "qr_data"]'::jsonb, optional_fields = '["passenger", "pnr", "train", "coach", "seat", "berth_type", "dep", "arr", "duration", "time", "date", "class", "quota", "pnr_status", "origin_platform", "dest_platform", "distance", "chart_status"]'::jsonb, updated_at = NOW() WHERE id = 'irctc';
UPDATE brands SET required_fields = '["origin", "destination", "qr_data"]'::jsonb, optional_fields = '["passenger", "flight", "seat", "pnr", "gate", "dep", "arr", "board_time", "duration", "time", "date", "origin_terminal", "dest_terminal", "terminal", "class", "loyalty_tier", "status", "boarding_zone"]'::jsonb, updated_at = NOW() WHERE id = 'indigo';
UPDATE brands SET required_fields = '["origin", "destination", "qr_data"]'::jsonb, optional_fields = '["passenger", "dep", "arr", "time", "duration", "booking_id", "line", "ticket_type", "fare", "origin_platform", "exit_gates", "stops", "issued_at", "valid_till"]'::jsonb, updated_at = NOW() WHERE id = 'namma-metro';
UPDATE brands SET required_fields = '["origin", "destination", "qr_data"]'::jsonb, optional_fields = '["passenger", "seat", "seat_type", "pnr", "bus", "bus_operator", "bus_number", "dep", "arr", "duration", "time", "date", "boarding_point", "drop_point", "driver_contact", "dep_label", "arr_label"]'::jsonb, updated_at = NOW() WHERE id = 'redbus';
UPDATE brands SET required_fields = '["name", "qr_data"]'::jsonb, optional_fields = '["vpa", "bank", "amount", "note", "account_mask", "txn_limit", "autopay_limit", "ifsc", "status"]'::jsonb, updated_at = NOW() WHERE id = 'upi';
UPDATE brands SET required_fields = '["restaurant", "booking_id"]'::jsonb, optional_fields = '["time", "date", "party_size", "table", "qr_data", "guest", "discount", "offer", "points", "member_id", "valid_thru", "tier", "status"]'::jsonb, updated_at = NOW() WHERE id = 'easydiner';
UPDATE brands SET required_fields = '["restaurant", "booking_id"]'::jsonb, optional_fields = '["time", "date", "party_size", "table", "table_area", "qr_data", "guest", "city", "special_tag", "cuisine", "grace_period"]'::jsonb, updated_at = NOW() WHERE id = 'zomato-dineout';
UPDATE brands SET required_fields = '["restaurant", "booking_id"]'::jsonb, optional_fields = '["time", "date", "party_size", "table", "qr_data", "guest", "offer_code", "discount", "bank_offer", "area", "valid_till", "min_order", "membership_status"]'::jsonb, updated_at = NOW() WHERE id = 'swiggy-dineout';
UPDATE brands SET required_fields = '["property", "booking_id"]'::jsonb, optional_fields = '["property_type", "address", "city", "check_in", "check_out", "check_in_time", "check_out_time", "guest", "guest_details", "door_pin", "host", "host_badge", "lock_brand", "wifi_ssid", "wifi_password", "status", "qr_data"]'::jsonb, updated_at = NOW() WHERE id = 'airbnb';
UPDATE brands SET required_fields = '["vehicle", "booking_id"]'::jsonb, optional_fields = '["pickup", "drop_off", "guest", "plate", "qr_data", "fuel", "range_km", "pickup_hub", "rental_duration", "door_pin", "key_status", "dl_verified", "km_limit", "roadside", "vehicle_type"]'::jsonb, updated_at = NOW() WHERE id = 'zoomcar';
